# First test to plot tif image files generated by QGIS
# The goal is to visualize shadow cast by buildings, canopy and terrain
# A. Iantchenko 17th april 2024
from osgeo import gdal
from numpy import linspace
from numpy import meshgrid
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap

# Not the actual ones we have, just an example
lowlong = 3.7 #lower left corner of longitude
lowlat = 57.7 #lower left corner of latitude
upplong = 31.3 #upper right corner of longitude
upplat = 71.2 #upper right corner of latitude

# Path to tif file 
pathToRaster = r'/home/aiantchenk/Documents/GIS/Goteborg_SWEREF99_1200/testPythonUmep/test_veg2.tif'
raster = gdal.Open(pathToRaster,1)
print(raster)
geo = raster.GetGeoTransform()
geo = raster.ReadAsArray()


mp = Basemap(projection='merc',
             llcrnrlon=lowlong,
             llcrnrlat=lowlat,
             urcrnrlon=upplong,
             urcrnrlat=upplat,
             resolution='i')

x = linspace(0,mp.urcrnrx,geo.shape[1])
y = linspace(0,mp.urcrnry,geo.shape[0])

xx,yy = meshgrid(x,y)
mp.pcolormesh(xx,yy,geo)

print(geo)

plt.show()